import SideBar from '@/components/SideBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className + "bg-gray-900"}>
				<div className="min-h-screen bg-slate-100 flex relative overflow-hidden">
					<SideBar currentPage={'home'} />
					<div className='w-[calc(100%-16rem)] py-3 pb-7 px-8 ml-64'>
						<Header />
						{children}
					</div>
				</div>
			</body>
		</html>
	)
}
